"""add_slug_column_to_products

Revision ID: 02e967582e29
Revises: 56dfa757df8b
Create Date: 2026-05-15 17:44:19.135831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '02e967582e29'
down_revision: Union[str, None] = '56dfa757df8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('slug', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('blocking_reason_id', app.models.base.GUID(), nullable=True))
    op.drop_column('skus', 'image_url')
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('cost_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('skus', sa.Column('discount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('products', 'blocking_reason_id')
    op.drop_column('products', 'slug')
    # ### end Alembic commands ###
