"""add reserved_quantity and sku_reservations

Revision ID: 0345df0c8c42
Revises: 81298b809358
Create Date: 2026-04-06 07:53:12.317029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0345df0c8c42'
down_revision: Union[str, None] = '81298b809358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sku_reservations', 'sku_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('skus', sa.Column('reserved_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'reserved_quantity')
    op.alter_column('sku_reservations', 'sku_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
