"""add_sku_fields_cost_price_discount_stock_quantity

Revision ID: 11886d062306
Revises: 02e967582e29
Create Date: 2026-05-15 18:25:57.657287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11886d062306'
down_revision: Union[str, None] = '02e967582e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('cost_price', sa.Integer(), nullable=False))
    op.add_column('skus', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('skus', sa.Column('stock_quantity', sa.Integer(), nullable=False))
    op.add_column('skus', sa.Column('active_quantity', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('article', sa.String(length=100), nullable=True))
    op.drop_column('skus', 'quantity')
    op.drop_column('skus', 'compare_at_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('compare_at_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('skus', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('skus', 'article')
    op.drop_column('skus', 'active_quantity')
    op.drop_column('skus', 'stock_quantity')
    op.drop_column('skus', 'image')
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###
