"""add_accepted_by_id_to_invoices

Revision ID: 2518f049a0ef
Revises: 238398bae69f
Create Date: 2026-05-29 15:59:52.151108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2518f049a0ef'
down_revision: Union[str, None] = '238398bae69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('accepted_by_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'invoices', 'sellers', ['accepted_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'accepted_by_id')
    # ### end Alembic commands ###
