"""remove_meta_fields_from_products

Revision ID: 2ce1621f6809
Revises: db058cf13944
Create Date: 2026-05-07 12:00:49.107553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce1621f6809'
down_revision: Union[str, None] = 'db058cf13944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_slug_key', 'products', type_='unique')
    op.drop_column('products', 'meta_title')
    op.drop_column('products', 'slug')
    op.drop_column('products', 'meta_keywords')
    op.drop_column('products', 'meta_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('meta_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('meta_keywords', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('slug', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('meta_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_unique_constraint('products_slug_key', 'products', ['slug'])
    # ### end Alembic commands ###
