"""add_cost_price_discount_image_to_sku

Revision ID: 56dfa757df8b
Revises: 2ce1621f6809
Create Date: 2026-05-10 17:31:30.512290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56dfa757df8b'
down_revision: Union[str, None] = '2ce1621f6809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skus', sa.Column('cost_price', sa.Integer(), nullable=False))
    op.add_column('skus', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('skus', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skus', 'image_url')
    op.drop_column('skus', 'discount')
    op.drop_column('skus', 'cost_price')
    # ### end Alembic commands ###
