"""initial_all_models

Revision ID: 6dc0e5d846ad
Revises: 
Create Date: 2026-05-30 19:16:50.031255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '6dc0e5d846ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', app.models.base.GUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_categories_is_active', 'categories', ['is_active'], unique=False)
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('ix_categories_path', 'categories', ['path'], unique=False)
    op.create_table('characteristics',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_characteristics_is_global', 'characteristics', ['is_global'], unique=False)
    op.create_index('ix_characteristics_type', 'characteristics', ['type'], unique=False)
    op.create_table('fulfill_operations',
    sa.Column('order_id', app.models.base.GUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('images',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_images_entity_id', 'images', ['entity_id'], unique=False)
    op.create_index('ix_images_entity_type', 'images', ['entity_type'], unique=False)
    op.create_index('ix_images_entity_type_entity_id', 'images', ['entity_type', 'entity_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sellers',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('legal_address', sa.String(length=500), nullable=True),
    sa.Column('actual_address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.create_index('ix_sellers_created_at', 'sellers', ['created_at'], unique=False)
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    op.create_index('ix_sellers_inn', 'sellers', ['inn'], unique=False)
    op.create_index('ix_sellers_is_active', 'sellers', ['is_active'], unique=False)
    op.create_index('ix_sellers_status', 'sellers', ['status'], unique=False)
    op.create_table('unreserve_operations',
    sa.Column('order_id', app.models.base.GUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index('ix_unreserve_operations_processed_at', 'unreserve_operations', ['processed_at'], unique=False)
    op.create_table('category_characteristics',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('category_id', app.models.base.GUID(), nullable=True),
    sa.Column('characteristic_id', app.models.base.GUID(), nullable=True),
    sa.Column('is_filter', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic_values',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('characteristic_id', app.models.base.GUID(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('seller_id', app.models.base.GUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['sellers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_accepted_at', 'invoices', ['accepted_at'], unique=False)
    op.create_index('ix_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.create_index('ix_invoices_seller_id', 'invoices', ['seller_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('seller_id', app.models.base.GUID(), nullable=False),
    sa.Column('category_id', app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_image_id', app.models.base.GUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('moderation_comment', sa.Text(), nullable=True),
    sa.Column('blocking_reason_id', app.models.base.GUID(), nullable=True),
    sa.Column('field_reports_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('characteristics_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['main_image_id'], ['product_images.id'], name='fk_product_main_image', use_alter=True),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_created_at', 'products', ['created_at'], unique=False)
    op.create_index('ix_products_deleted', 'products', ['deleted'], unique=False)
    op.create_index('ix_products_seller_id', 'products', ['seller_id'], unique=False)
    op.create_index('ix_products_slug', 'products', ['slug'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    op.create_table('product_characteristics',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=True),
    sa.Column('characteristic_id', app.models.base.GUID(), nullable=True),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('characteristic_value_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['characteristic_value_id'], ['characteristic_values.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_characteristics_characteristic_id', 'product_characteristics', ['characteristic_id'], unique=False)
    op.create_index('ix_product_characteristics_product_id', 'product_characteristics', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_images_is_main', 'product_images', ['is_main'], unique=False)
    op.create_index('ix_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_index('ix_product_images_sort_order', 'product_images', ['sort_order'], unique=False)
    op.create_table('product_status_history',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=True),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by', app.models.base.GUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_status_history_changed_by', 'product_status_history', ['changed_by'], unique=False)
    op.create_index('ix_product_status_history_created_at', 'product_status_history', ['created_at'], unique=False)
    op.create_index('ix_product_status_history_new_status', 'product_status_history', ['new_status'], unique=False)
    op.create_index('ix_product_status_history_product_id', 'product_status_history', ['product_id'], unique=False)
    op.create_table('skus',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('product_id', app.models.base.GUID(), nullable=False),
    sa.Column('seller_sku', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('active_quantity', sa.Integer(), nullable=True),
    sa.Column('reserved_quantity', sa.Integer(), nullable=True),
    sa.Column('article', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('main_image_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['main_image_id'], ['product_images.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_skus_active_quantity', 'skus', ['active_quantity'], unique=False)
    op.create_index('ix_skus_article', 'skus', ['article'], unique=False)
    op.create_index('ix_skus_barcode', 'skus', ['barcode'], unique=False)
    op.create_index('ix_skus_is_active', 'skus', ['is_active'], unique=False)
    op.create_index('ix_skus_price', 'skus', ['price'], unique=False)
    op.create_index('ix_skus_product_id', 'skus', ['product_id'], unique=False)
    op.create_index('ix_skus_seller_sku', 'skus', ['seller_sku'], unique=False)
    op.create_table('fulfill_operation_items',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('operation_order_id', app.models.base.GUID(), nullable=False),
    sa.Column('sku_id', app.models.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_order_id'], ['fulfill_operations.order_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_items',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('invoice_id', app.models.base.GUID(), nullable=False),
    sa.Column('sku_id', app.models.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('accepted_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_items_sku_id', 'invoice_items', ['sku_id'], unique=False)
    op.create_table('sku_characteristics',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('sku_id', app.models.base.GUID(), nullable=True),
    sa.Column('characteristic_id', app.models.base.GUID(), nullable=True),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.Column('value_int', sa.Integer(), nullable=True),
    sa.Column('value_float', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('characteristic_value', app.models.base.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['characteristic_value'], ['characteristic_values.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sku_characteristics_characteristic_id', 'sku_characteristics', ['characteristic_id'], unique=False)
    op.create_index('ix_sku_characteristics_sku_id', 'sku_characteristics', ['sku_id'], unique=False)
    op.create_table('sku_images',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('sku_id', app.models.base.GUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sku_images_sku_id', 'sku_images', ['sku_id'], unique=False)
    op.create_index('ix_sku_images_sort_order', 'sku_images', ['sort_order'], unique=False)
    op.create_table('sku_reservations',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('sku_id', app.models.base.GUID(), nullable=False),
    sa.Column('order_id', app.models.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sku_reservations_expires_at', 'sku_reservations', ['expires_at'], unique=False)
    op.create_index('ix_sku_reservations_order_id', 'sku_reservations', ['order_id'], unique=False)
    op.create_index('ix_sku_reservations_sku_id', 'sku_reservations', ['sku_id'], unique=False)
    op.create_index('ix_sku_reservations_status', 'sku_reservations', ['status'], unique=False)
    op.create_index('ix_sku_reservations_status_expires_at', 'sku_reservations', ['status', 'expires_at'], unique=False)
    op.create_table('unreserve_operation_items',
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('operation_order_id', app.models.base.GUID(), nullable=False),
    sa.Column('sku_id', app.models.base.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_order_id'], ['unreserve_operations.order_id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unreserve_operation_items_operation_order_id', 'unreserve_operation_items', ['operation_order_id'], unique=False)
    op.create_index('ix_unreserve_operation_items_sku_id', 'unreserve_operation_items', ['sku_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unreserve_operation_items_sku_id', table_name='unreserve_operation_items')
    op.drop_index('ix_unreserve_operation_items_operation_order_id', table_name='unreserve_operation_items')
    op.drop_table('unreserve_operation_items')
    op.drop_index('ix_sku_reservations_status_expires_at', table_name='sku_reservations')
    op.drop_index('ix_sku_reservations_status', table_name='sku_reservations')
    op.drop_index('ix_sku_reservations_sku_id', table_name='sku_reservations')
    op.drop_index('ix_sku_reservations_order_id', table_name='sku_reservations')
    op.drop_index('ix_sku_reservations_expires_at', table_name='sku_reservations')
    op.drop_table('sku_reservations')
    op.drop_index('ix_sku_images_sort_order', table_name='sku_images')
    op.drop_index('ix_sku_images_sku_id', table_name='sku_images')
    op.drop_table('sku_images')
    op.drop_index('ix_sku_characteristics_sku_id', table_name='sku_characteristics')
    op.drop_index('ix_sku_characteristics_characteristic_id', table_name='sku_characteristics')
    op.drop_table('sku_characteristics')
    op.drop_index('ix_invoice_items_sku_id', table_name='invoice_items')
    op.drop_index('ix_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_table('fulfill_operation_items')
    op.drop_index('ix_skus_seller_sku', table_name='skus')
    op.drop_index('ix_skus_product_id', table_name='skus')
    op.drop_index('ix_skus_price', table_name='skus')
    op.drop_index('ix_skus_is_active', table_name='skus')
    op.drop_index('ix_skus_barcode', table_name='skus')
    op.drop_index('ix_skus_article', table_name='skus')
    op.drop_index('ix_skus_active_quantity', table_name='skus')
    op.drop_table('skus')
    op.drop_index('ix_product_status_history_product_id', table_name='product_status_history')
    op.drop_index('ix_product_status_history_new_status', table_name='product_status_history')
    op.drop_index('ix_product_status_history_created_at', table_name='product_status_history')
    op.drop_index('ix_product_status_history_changed_by', table_name='product_status_history')
    op.drop_table('product_status_history')
    op.drop_index('ix_product_images_sort_order', table_name='product_images')
    op.drop_index('ix_product_images_product_id', table_name='product_images')
    op.drop_index('ix_product_images_is_main', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('ix_product_characteristics_product_id', table_name='product_characteristics')
    op.drop_index('ix_product_characteristics_characteristic_id', table_name='product_characteristics')
    op.drop_table('product_characteristics')
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_slug', table_name='products')
    op.drop_index('ix_products_seller_id', table_name='products')
    op.drop_index('ix_products_deleted', table_name='products')
    op.drop_index('ix_products_created_at', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_seller_id', table_name='invoices')
    op.drop_index('ix_invoices_created_at', table_name='invoices')
    op.drop_index('ix_invoices_accepted_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('characteristic_values')
    op.drop_table('category_characteristics')
    op.drop_index('ix_unreserve_operations_processed_at', table_name='unreserve_operations')
    op.drop_table('unreserve_operations')
    op.drop_index('ix_sellers_status', table_name='sellers')
    op.drop_index('ix_sellers_is_active', table_name='sellers')
    op.drop_index('ix_sellers_inn', table_name='sellers')
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.drop_index('ix_sellers_created_at', table_name='sellers')
    op.drop_table('sellers')
    op.drop_table('outbox_events')
    op.drop_index('ix_images_entity_type_entity_id', table_name='images')
    op.drop_index('ix_images_entity_type', table_name='images')
    op.drop_index('ix_images_entity_id', table_name='images')
    op.drop_table('images')
    op.drop_table('fulfill_operations')
    op.drop_index('ix_characteristics_type', table_name='characteristics')
    op.drop_index('ix_characteristics_is_global', table_name='characteristics')
    op.drop_table('characteristics')
    op.drop_index('ix_categories_path', table_name='categories')
    op.drop_index('ix_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_is_active', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
