"""add_field_reports_json_to_products

Revision ID: ba030ac35ab0
Revises: 11886d062306
Create Date: 2026-05-16 17:45:29.296027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba030ac35ab0'
down_revision: Union[str, None] = '11886d062306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('field_reports_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'field_reports_json')
    # ### end Alembic commands ###
