"""initial_migration

Revision ID: db058cf13944
Revises: b6ede748495b
Create Date: 2026-05-07 11:33:15.501218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db058cf13944'
down_revision: Union[str, None] = 'b6ede748495b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_product_main_image', 'products', 'product_images', ['main_image_id'], ['id'], use_alter=True)
    op.alter_column('sellers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sellers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_sellers_email'), 'sellers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sellers_email'), table_name='sellers')
    op.alter_column('sellers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('sellers', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('fk_product_main_image', 'products', type_='foreignkey')
    # ### end Alembic commands ###
