"""add_invoices_and_invoice_items

Revision ID: eb93ae4b42cf
Revises: ba030ac35ab0
Create Date: 2026-05-25 07:24:42.343900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb93ae4b42cf'
down_revision: Union[str, None] = 'ba030ac35ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'price')
    op.add_column('invoices', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint('unique_seller_invoice', 'invoices', type_='unique')
    op.drop_column('invoices', 'invoice_number')
    op.drop_column('invoices', 'received_at')
    op.drop_column('invoices', 'warehouse_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('invoice_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('unique_seller_invoice', 'invoices', ['seller_id', 'invoice_number'])
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('invoices', 'accepted_at')
    op.add_column('invoice_items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
